# Generated by Django 4.1.4 on 2022-12-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPost',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_title', models.CharField(max_length=50)),
                ('album_subtitle', models.CharField(default='', max_length=200)),
                ('album_image', models.ImageField(default='', upload_to='static/images')),
                ('album_area', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
