# Generated by Django 4.1.4 on 2022-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpost',
            name='album_image',
            field=models.FileField(default='', max_length=300, null=True, upload_to='images/'),
        ),
    ]
