# Generated by Django 4.1.4 on 2022-12-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0008_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='article_body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
    ]
